### ISSUE TITLE
Unpickling error for inputs in classification notebook

### ISSUE THREAD

**Issue by mohsaied** [fhalab/channels#2]
I think the inputs/props.pkl may be corrupted? I can's seem to be able to unpickle it (see error below)

---------------------------------------------------------------------------
```
UnpicklingError                           Traceback (most recent call last)
<ipython-input-8-9ad326ac7968> in <module>
      1 with open('../inputs/props.pkl', 'rb') as f:
----> 2     df = pickle.load(f)
      3 df.head()

UnpicklingError: invalid load key, 'v'.
```

**Comment by mohsaied** [comment]
seems to be a git lfs issue.. still looking into it

**Comment by mohsaied** [comment]
cloning with git LFS installed also errors out with:

`Pointer file error: Unable to parse pointer at: "regression/inputs/alignment_and_contacts_C1C2.pkl"`

**Comment by mohsaied** [comment]
`Downloading classification/inputs/2GFP_above_parent123457.pkl (1.2 GB)                                                                                                                                    Error downloading object: classification/inputs/2GFP_above_parent123457.pkl (12d1974): Smudge error: Error downloading classification/inputs/2GFP_above_parent123457.pkl (12d19745f73a6d7cab15890a3cbcd3f70f2ad268f7ca201879532b0677f9cfa2): [12d19745f73a6d7cab15890a3cbcd3f70f2ad268f7ca201879532b0677f9cfa2] Object does not exist on the server: [404] Object does not exist on the server                                            `

**Comment by mohsaied** [comment]
Can you maybe upload files to gdrive or something else? or fix the LFS issue? This work is not reproducible like this..

**Comment by yangkky** [comment]
I've uploaded all the classification inputs to google [drive](https://drive.google.com/file/d/1g1DWEKEFq0-u5uW9HicVNPK4yTuxu04e/view?usp=sharing). See if that works for you. 

Ideally, I'd go through and fix the underlying git lfs issues, but this should be a good stopgap.

**Comment by mohsaied** [comment]
great thanks, closing this issue as bug is not related to pickle
